name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Remove existing image
      run: docker rm -f remington.boo
    - name: Build the Docker image
      run: docker build -t remington.boo .
    - name: Run docker image
      run: docker run --name remington.boo -p 4000:3000 -d --restart unless-stopped remington.boo
